repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
  - id: black
    language_version: python
- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
