repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
  - id: black
    language_version: python
- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies:
      - flake8-bugbear
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]
