site_name: Dagger - Distributed Data Pipelines in Python
site_url: https://larribas.me/dagger
site_description: Documentation portal for the Dagger (py-dagger) Python library.
site_author: Lorenzo Arribas (@larribas)
copyright: "2021, Lorenzo Arribas (@larribas)"
repo_url: https://github.com/larribas/dagger
theme: readthedocs
nav:
- Overview: README.md
- Releases ⧉: https://github.com/larribas/dagger/releases
- PyPI ⧉: https://pypi.org/project/py-dagger/
