name: Publish Package

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PYTHON: 3.9.6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON }}
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.5
      - name: Install poetry-dynamic-versioning
        run: pip install poetry-dynamic-versioning
      - name: Poetry Install
        run: poetry install
      - name: Git Tags
        run: git tag
      - name: Poetry Build
        run: poetry build
      # - name: Poetry Publish
      #   run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}

