name: Publish Docs in GH Pages

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'larribas/dagger'
    runs-on: ubuntu-latest
    env:
      PYTHON: 3.9.6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON }}
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.5
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-${{ env.PYTHON}}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: make install
      - name: Publish documentation
        run: make docs-publish
