name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        # - windows-latest  Commented out until issue #17 is addressed
        python: ["3.8", "3.9"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.5
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-${{ matrix.python }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          make install
      - name: Unit tests
        run: |
          make test
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          env_vars: OS,PYTHON
          verbose: true

